# Generated by Django 5.1.1 on 2025-03-27 15:30

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_documentchunk_embedding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentchunk',
            name='embedding',
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='vector_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]