# Generated by Django 5.1.1 on 2025-04-16 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_document_file_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='document',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conversation', to='documents.document'),
        ),
    ]
